/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DexERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexERC20__factory>;
    getContractFactory(
      name: "DexFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexFactory__factory>;
    getContractFactory(
      name: "DexPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexPool__factory>;
    getContractFactory(
      name: "DexRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexRouter__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "DexLibraryTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DexLibraryTest__factory>;
    getContractFactory(
      name: "MathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MathTest__factory>;
    getContractFactory(
      name: "TokenTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenTest__factory>;

    getContractAt(
      name: "DexERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DexERC20>;
    getContractAt(
      name: "DexFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DexFactory>;
    getContractAt(
      name: "DexPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DexPool>;
    getContractAt(
      name: "DexRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DexRouter>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "DexLibraryTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DexLibraryTest>;
    getContractAt(
      name: "MathTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MathTest>;
    getContractAt(
      name: "TokenTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenTest>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
